image:
  repository: httpd
  tag: "2.4.68"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "50m"
    memory: "32Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

readinessProbe:
  path: /
  initialDelaySeconds: 2
  periodSeconds: 5

livenessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10